### ISSUE TITLE
Error loading Author-Email in some environments

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/coherent.build#51]
I'm getting this error attempting to release coherent.docs:

```

19s
Run pipx run coherent.cli build
  pipx run coherent.cli build
  pipx run twine upload dist/*
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    FORCE_COLOR: 1
    PIP_DISABLE_PIP_VERSION_CHECK: true
    PIP_NO_WARN_SCRIPT_LOCATION: true
    PYTHONSAFEPATH: 1
    pythonLocation: /opt/hostedtoolcache/Python/3.14.2/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.14.2/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.14.2/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.14.2/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.14.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.14.2/x64/lib
    TWINE_PASSWORD: ***
    GH_TOKEN: ***
creating virtual environment...
installing coherent-cli...
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - coherent.build
* Getting build dependencies for sdist...
* Building sdist...
/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/setuptools_scm/git.py:202: UserWarning: "/home/runner/work/coherent.docs/coherent.docs" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/setuptools_scm/git.py:202: UserWarning: "/home/runner/work/coherent.docs/coherent.docs" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
Traceback (most recent call last):
  File "/opt/pipx/.cache/a124c48ee7d93cf/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
  File "/opt/pipx/.cache/a124c48ee7d93cf/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/.cache/a124c48ee7d93cf/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/coherent/build/backend.py", line 81, in build_sdist
    consume(itertools.starmap(tf.addfile, layout.add_files()))
  File "/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/more_itertools/recipes.py", line 204, in consume
    deque(iterator, maxlen=0)
  File "/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/coherent/build/layouts.py", line 84, in <genexpr>
    return (
           ^
  File "/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/coherent/build/flit.py", line 114, in gen_files
    yield 'pyproject.toml', render(self.metadata)
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/coherent/build/flit.py", line 54, in render
    project = dict(project=metadata.render_toml() | entry_points())
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/coherent/build/metadata.py", line 147, in render_toml
    "authors": [self.author],
                ^^^^^^^^^^^
  File "/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/coherent/build/metadata.py", line 89, in author
    return self.parse_contributor(self['Author-Email'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-rsp7jjka/lib/python3.12/site-packages/coherent/build/metadata.py", line 94, in parse_contributor
    return exp.match(combined).groupdict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groupdict'
ERROR Backend subprocess exited when trying to invoke build_sdist

Error: Process completed with exit code 1.
```

**Comment by jaraco** [comment]
The issue seems only to happen on Python 3.12. If I use a Python 3.13 environment, the error doesn't occur.

I've traced the issue to the `author_from_vcs()` call, which is returning None, probably due to a trapped exception.

https://github.com/coherent-oss/coherent.build/blob/9dda0598edcc199837dcb89b6b2d7a7793ba86e7/discovery.py#L307-L324

It seems that `contribs` is empty.

Weird, it seems that types.SimpleNamespace is rejecting positional arguments.

```
Pdb) dict(zip(fame['columns'], fame['data'][0]))
{'Author': 'copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>', 'loc': 206, 'coms': 11, 'fils': 7, '%loc': 89.6, '%coms': 73.3, '%fils': 77.8}
(Pdb) types.SimpleNamespace(dict(zip(fame['columns'], fame['data'][0])))
*** TypeError: no positional arguments expected
```

**Comment by jaraco** [comment]
It must have been broken in 7abac077f54273ba234b80340a2aaff0724ba9c6, where that line was introduced, and I only tested/ran it on Python 3.13, which [introduced support](7abac077f54273ba234b80340a2aaff0724ba9c6) for the positional parameter.

**Comment by jaraco** [comment]
I was trying to figure out why the tests didn't catch this issue, but it seems they did.
